const characters = [
  // ── S TIER ──
  {
    id: 1,
    name: "Bakugo",
    tier: "S",
    role: "Melee",
    bestCostume: "Strafe Panzer",
    costumes: [
      { name: "Strafe Panzer", best: true },
      { name: "Hero Costume ver. 1", best: false },
      { name: "Cyber Hero Costume", best: false },
      { name: "Quirk Assist Gear", best: false },
      { name: "All Might ver.", best: false },
    ],
    tuning: [
      "Quirk Skill α Attack Power+ — increases AP Shot damage",
      "Quirk Skill γ Attack Power+ — boosts Cluster/Machine Gun",
      "Wall Jump Height+ — improves aerial mobility",
      "PU/PC Reload Speed+ — faster grenade reloads",
      "Special Tune: Revenge Strike — burst damage after taking a hit",
    ],
    tips: "Bakugo is the #1 character in the current meta. His aerial mobility is unmatched — always stay airborne. Use AP Shot to poke at range, then close with Explosion Rush. Strafe Panzer costume gives the best stat bonuses. Tune for Alpha damage first.",
    video: { label: "Bakugo Combo Guide", url: "https://www.youtube.com/results?search_query=bakugo+my+hero+ultra+rumble+combo+guide" },
  },
  {
    id: 2,
    name: "Deku",
    tier: "S",
    role: "Melee",
    bestCostume: "Full Cowling 100%",
    costumes: [
      { name: "Full Cowling 100%", best: true },
      { name: "Cyber Hero Costume", best: false },
      { name: "Gran Torino ver.", best: false },
      { name: "Kung Fu Outfit", best: false },
      { name: "Hero Costume ver. 1", best: false },
    ],
    tuning: [
      "Quirk Skill γ Defense+ — reduces damage taken from Gamma skills",
      "Quirk Skill α Attack Power+ — boosts Delaware Smash",
      "Dash Distance+ — extends gap-closing range",
      "HP+ — extra survivability in late game",
      "Special Tune: Ability Manifest — increases quirk power over time",
    ],
    tips: "Deku is a top-tier aggressive character. Full Cowling 100% is the strongest costume — it increases all stat values. Delaware Smash is your main combo starter. Use Blackwhip to grapple and reposition fast. Always tune Gamma Defense first to survive burst damage.",
    video: { label: "Deku Combo Guide", url: "https://www.youtube.com/results?search_query=deku+my+hero+ultra+rumble+combo+guide" },
  },
  {
    id: 3,
    name: "All Might",
    tier: "S",
    role: "Melee",
    bestCostume: "Golden Age Hero",
    costumes: [
      { name: "Golden Age Hero", best: true },
      { name: "Silver Age Hero", best: false },
      { name: "Hero Costume ver. 1", best: false },
      { name: "Gatling Smash ver.", best: false },
    ],
    tuning: [
      "HP Defense+ — reduces incoming damage",
      "Melee Attack Power+ — boosts all smash moves",
      "Vertical Jump Height+ — improves aerial Gatling Smash",
      "HP+ — increases total health pool",
      "Special Tune: Willpower — survive one hit that would KO you",
    ],
    tips: "All Might is S-tier for his massive knockback and HP pool. His smashes deal the highest raw damage in the game. Gatling variant lets him spam aerial attacks. Willpower is his best Special Tune — it lets him survive clutch moments. Weak at range so always push forward.",
    video: { label: "All Might Combo Guide", url: "https://www.youtube.com/results?search_query=all+might+my+hero+ultra+rumble+combo+guide" },
  },
  {
    id: 4,
    name: "Toga",
    tier: "S",
    role: "Support / Melee",
    bestCostume: "League of Villains",
    costumes: [
      { name: "League of Villains", best: true },
      { name: "School Uniform", best: false },
      { name: "Villain Style Alt", best: false },
    ],
    tuning: [
      "PU/PC Reload Speed+ — faster blood meter refill",
      "Quirk Skill β Attack Power+ — boosts Transform damage",
      "Move Speed+ — faster repositioning",
      "HP+ — survivability outside Transform",
      "Special Tune: Quirk Factor Release — enhances Transform copied quirk",
    ],
    tips: "Toga is a high-skill character that rewards practice. Transform lets her copy any enemy and use their moves — transform into Bakugo or Deku for maximum damage. Blood drain heals her between fights. Her League of Villains costume has the best stat spread.",
    video: { label: "Toga Combo Guide", url: "https://www.youtube.com/results?search_query=toga+my+hero+ultra+rumble+combo+guide" },
  },
  {
    id: 5,
    name: "Yaoyorozu",
    tier: "S",
    role: "Support",
    bestCostume: "Hero Costume ver. 2",
    costumes: [
      { name: "Hero Costume ver. 2", best: true },
      { name: "Hero Costume ver. 1", best: false },
      { name: "UA Sports Festival", best: false },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "Quirk Skill α Reload Speed+ — faster item creation",
      "HP Defense+ — protects her low mobility",
      "PU/PC Duration+ — extends created item uptime",
      "HP+ — compensates for support playstyle",
      "Special Tune: Ability Manifest — strengthens all creation quirk effects",
    ],
    tips: "Yaoyorozu is an S-tier support. She can create shields, cannons, and items for the whole team. Position safely behind teammates and create support items constantly. Her value explodes in team fights where she can heal and buff allies. Hard to use solo — shine in coordinated teams.",
    video: { label: "Yaoyorozu Combo Guide", url: "https://www.youtube.com/results?search_query=yaoyorozu+my+hero+ultra+rumble+guide" },
  },
  {
    id: 6,
    name: "Ibara",
    tier: "S",
    role: "Ranged / Support",
    bestCostume: "Hero Costume ver. 1",
    costumes: [
      { name: "Hero Costume ver. 1", best: true },
      { name: "School Uniform", best: false },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "Quirk Skill α Attack Power+ — boosts Vines of Punishment",
      "PU/PC Reload Speed+ — faster vine deployment",
      "Range+ — extends vine reach",
      "HP Defense+ — survivability",
      "Special Tune: Willpower — survive one KO hit",
    ],
    tips: "Ibara is a top-tier zone control character. Her vines trap enemies in place giving teammates easy follow-up kills. Plant vines at choke points and high-traffic areas. Her ranged vines make her very safe to play. Excellent with any team comp.",
    video: { label: "Ibara Combo Guide", url: "https://www.youtube.com/results?search_query=ibara+my+hero+ultra+rumble+guide" },
  },

  // ── A TIER ──
  {
    id: 7,
    name: "Tsuyu",
    tier: "A",
    role: "Melee / Support",
    bestCostume: "Hero Costume ver. 2",
    costumes: [
      { name: "Hero Costume ver. 2", best: true },
      { name: "Hero Costume ver. 1", best: false },
      { name: "School Uniform", best: false },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "Quirk Skill α Attack Power+ — boosts Tongue Lash",
      "Move Speed+ — improves chase and escape",
      "Dash Distance+ — better mobility",
      "HP+ — survivability",
      "Special Tune: Revenge Strike — counter-attack after being hit",
    ],
    tips: "Tsuyu excels at hit-and-run tactics. Tongue Lash pulls enemies in for combos. Her wall-cling and swim abilities let her reach unusual angles. Strong at flanking isolated targets. In team fights use her to peel for supports.",
    video: { label: "Tsuyu Combo Guide", url: "https://www.youtube.com/results?search_query=tsuyu+froppy+my+hero+ultra+rumble+combo" },
  },
  {
    id: 8,
    name: "Kaminari",
    tier: "A",
    role: "Ranged",
    bestCostume: "Hero Costume ver. 2",
    costumes: [
      { name: "Hero Costume ver. 2", best: true },
      { name: "Hero Costume ver. 1", best: false },
      { name: "UA Sports Festival", best: false },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "Quirk Skill α Attack Power+ — boosts Indiscriminate Shock",
      "Range+ — extends lightning reach",
      "Quirk Skill γ Reload Speed+ — faster discharge recovery",
      "HP Defense+ — protects him after Warp discharge",
      "Special Tune: Ability Manifest — enhances electric output",
    ],
    tips: "Kaminari has massive area damage with his electric attacks. Indiscriminate Shock is one of the best crowd control tools in the game. After using Warp (going brain-dead) position yourself safely so teammates can protect you. Great pick in tight indoor areas.",
    video: { label: "Kaminari Combo Guide", url: "https://www.youtube.com/results?search_query=kaminari+my+hero+ultra+rumble+combo" },
  },
  {
    id: 9,
    name: "Mount Lady",
    tier: "A",
    role: "Melee / Tank",
    bestCostume: "Hero Costume ver. 1",
    costumes: [
      { name: "Hero Costume ver. 1", best: true },
      { name: "Casual Wear", best: false },
      { name: "Gigantification Form", best: false },
    ],
    tuning: [
      "HP+ — boosts her large health pool",
      "Melee Attack Power+ — increases Gigantification damage",
      "HP Defense+ — tankier in Gigantification form",
      "Move Speed+ — helps mini form mobility",
      "Special Tune: Willpower — survive one KO hit while giant",
    ],
    tips: "Mount Lady is a powerful tank. Her Gigantification turns her into a massive AoE threat. Use mini form to approach safely, then Gigantify to zone entire areas. Her giant form can block paths and destroy cover. Strong at protecting objectives and controlling circles.",
    video: { label: "Mount Lady Combo Guide", url: "https://www.youtube.com/results?search_query=mount+lady+my+hero+ultra+rumble+guide" },
  },
  {
    id: 10,
    name: "Todoroki",
    tier: "A",
    role: "Ranged / Melee",
    bestCostume: "Hero Costume Alpha",
    costumes: [
      { name: "Hero Costume Alpha", best: true },
      { name: "Hero Costume Beta", best: false },
      { name: "Hero Costume Gamma", best: false },
      { name: "Kung Fu Outfit", best: false },
      { name: "Casual Style", best: false },
    ],
    tuning: [
      "Quirk Skill α Attack Power+ — boosts ice/fire Gamma skill",
      "Quirk Skill β Reload Speed+ — faster Heaven-Piercing Ice Wall",
      "Range+ — extends Glacial Terrain reach",
      "HP+ — general survivability",
      "Special Tune: Ability Manifest — enhances half-cold half-hot output",
    ],
    tips: "Todoroki is a versatile zone-controller. Use Glacial Terrain to freeze floors and slow enemies, then punish with fire combos. Heaven-Piercing Ice Wall cuts off escapes and creates cover. Hero Costume Alpha gives the most balanced stat bonuses. Weak to burst melee at close range.",
    video: { label: "Todoroki Combo Guide", url: "https://www.youtube.com/results?search_query=todoroki+my+hero+ultra+rumble+combo" },
  },
  {
    id: 11,
    name: "Shigaraki",
    tier: "A",
    role: "Melee",
    bestCostume: "League of Villains Leader",
    costumes: [
      { name: "League of Villains Leader", best: true },
      { name: "Villain Casual", best: false },
      { name: "Decay Form", best: false },
    ],
    tuning: [
      "Melee Attack Power+ — boosts all Decay melee hits",
      "Quirk Skill α Attack Power+ — increases Scatter damage",
      "Guard Break Recovery+ — faster recovery after guard breaks",
      "HP Defense+ — survivability in close range",
      "Special Tune: Revenge Strike — punish enemies who hit you",
    ],
    tips: "Shigaraki is lethal at close range. Decay destroys cover and deals massive AoE damage. Always approach from angles — he dies fast to sustained ranged fire. His guard break on Scatter is great for cracking defensive players. Best in tight areas where Decay does the most damage.",
    video: { label: "Shigaraki Combo Guide", url: "https://www.youtube.com/results?search_query=shigaraki+my+hero+ultra+rumble+combo" },
  },
  {
    id: 12,
    name: "Cementoss",
    tier: "A",
    role: "Support / Tank",
    bestCostume: "Hero Costume ver. 1",
    costumes: [
      { name: "Hero Costume ver. 1", best: true },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "PU/PC Duration+ — extends cement wall uptime",
      "HP+ — larger health pool",
      "Quirk Skill α Attack Power+ — harder cement projectiles",
      "HP Defense+ — tough frontline presence",
      "Special Tune: Willpower — survive one KO hit",
    ],
    tips: "Cementoss is invaluable for team play. His cement walls control entire zones and block enemy movement. Build walls to protect teammates, cut off enemy rotations, or create cover in open areas. Very underrated — one of the best supports in coordinated play.",
    video: { label: "Cementoss Guide", url: "https://www.youtube.com/results?search_query=cementoss+my+hero+ultra+rumble+guide" },
  },

  // ── B TIER ──
  {
    id: 13,
    name: "Kirishima",
    tier: "B",
    role: "Melee / Tank",
    bestCostume: "Hero Costume: Hardening",
    costumes: [
      { name: "Hero Costume: Hardening", best: true },
      { name: "UA Sports Festival", best: false },
      { name: "Unbreakable Form", best: false },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "HP Defense+ — reduces damage while Hardening is active",
      "Melee Attack Power+ — boosts Red Riot Unbreakable",
      "HP+ — more health for tanking",
      "Knockback Resistance+ — stay grounded in heavy fights",
      "Special Tune: Willpower — survive one KO hit",
    ],
    tips: "Kirishima is a solid frontline tank. Hardening lets you walk through damage and counter-attack. Unbreakable is a game-changer when activated at low HP. Best role is drawing enemy fire while teammates deal damage. Struggles against ranged characters who kite him.",
    video: { label: "Kirishima Combo Guide", url: "https://www.youtube.com/results?search_query=kirishima+my+hero+ultra+rumble+combo" },
  },
  {
    id: 14,
    name: "Dabi",
    tier: "B",
    role: "Ranged",
    bestCostume: "League of Villains",
    costumes: [
      { name: "League of Villains", best: true },
      { name: "Villain Casual", best: false },
      { name: "Blueflame Alt", best: false },
    ],
    tuning: [
      "Quirk Skill α Attack Power+ — increases Cremation damage",
      "PU/PC Duration+ — longer burn duration on floors",
      "Range+ — extends Jet Burn reach",
      "Quirk Skill γ Reload Speed+ — faster Blue Flame Barrage",
      "Special Tune: Ability Manifest — enhances blue fire output",
    ],
    tips: "Dabi controls zones with blue fire that burns the floor. Spread flames to deny areas and force enemies into bad positions. Blue Flame Barrage is a strong combo ender. He's dropped to B-tier because top-tier characters can outrun and pressure him — keep distance and play smart.",
    video: { label: "Dabi Combo Guide", url: "https://www.youtube.com/results?search_query=dabi+my+hero+ultra+rumble+combo" },
  },
  {
    id: 15,
    name: "Uraraka",
    tier: "B",
    role: "Support / Melee",
    bestCostume: "Hero Costume ver. 2",
    costumes: [
      { name: "Hero Costume ver. 2", best: true },
      { name: "Kunoichi", best: false },
      { name: "Superstar Idol", best: false },
      { name: "Christmas Santa Costume", best: false },
      { name: "UA Sports Festival", best: false },
    ],
    tuning: [
      "Quirk Skill α Reload Speed+ — faster Zero Gravity recharge",
      "Quirk Skill β Attack Power+ — boosts Meteor Storm",
      "Air Move Speed+ — better aerial mobility",
      "HP+ — survivability",
      "Special Tune: Quirk Factor Release — enhances floating effects",
    ],
    tips: "Uraraka excels at setting up kills. Float enemies with Zero Gravity then slam them with Meteor Storm. She's weaker in direct 1v1 but shines in team fights where allies can follow up on floated targets. Kunoichi costume is a fun alt with no stat penalty.",
    video: { label: "Uraraka Combo Guide", url: "https://www.youtube.com/results?search_query=uraraka+my+hero+ultra+rumble+combo" },
  },
  {
    id: 16,
    name: "Iida",
    tier: "B",
    role: "Melee",
    bestCostume: "Hero Costume ver. 2",
    costumes: [
      { name: "Hero Costume ver. 2", best: true },
      { name: "Hero Costume ver. 1", best: false },
      { name: "UA Sports Festival", best: false },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "Move Speed+ — enhances Engine Leg burst speed",
      "Quirk Skill α Attack Power+ — boosts Recipro Burst damage",
      "Dash Distance+ — extends Recipro Extend charge",
      "HP+ — survivability",
      "Special Tune: Ability Manifest — improves engine output",
    ],
    tips: "Iida is a high-speed character who excels at hit-and-run. Recipro Burst gives him the fastest movement in the game temporarily. Use it to dash through enemies, deal damage, and escape before they can counter. Hard to master but rewarding at high level play.",
    video: { label: "Iida Combo Guide", url: "https://www.youtube.com/results?search_query=iida+my+hero+ultra+rumble+combo" },
  },
  {
    id: 17,
    name: "Kendo",
    tier: "B",
    role: "Melee",
    bestCostume: "Hero Costume ver. 1",
    costumes: [
      { name: "Hero Costume ver. 1", best: true },
      { name: "School Uniform", best: false },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "Quirk Skill α Attack Power+ — boosts Big Fist damage",
      "Melee Attack Power+ — increases all giant-hand hits",
      "HP Defense+ — tankier during Big Fist swings",
      "HP+ — survivability",
      "Special Tune: Revenge Strike — hit back after taking damage",
    ],
    tips: "Kendo's Big Fist Quirk gives her massive reach and strong knockback. Use enlarged fists to swat multiple enemies at once. Good at interrupting enemy combos. She's straightforward to play — get in close and keep swinging. Struggles against fast characters who can dodge her slow swings.",
    video: { label: "Kendo Combo Guide", url: "https://www.youtube.com/results?search_query=kendo+my+hero+ultra+rumble+guide" },
  },

  // ── C TIER ──
  {
    id: 18,
    name: "Mr. Compress",
    tier: "C",
    role: "Support",
    bestCostume: "League of Villains",
    costumes: [
      { name: "League of Villains", best: true },
      { name: "Villain Casual", best: false },
      { name: "Masked Performer", best: false },
    ],
    tuning: [
      "Quirk Skill α Reload Speed+ — faster Compress recharge",
      "Range+ — extends marble throw distance",
      "HP+ — survivability",
      "Move Speed+ — better repositioning",
      "Special Tune: Willpower — survive one KO hit",
    ],
    tips: "Mr. Compress compresses enemies into marbles, temporarily removing them from combat. His utility is high but he needs teammates to follow up. In solo play he's weak — in a coordinated team he can turn fights. Currently C-tier because top characters can escape his Compress easily.",
    video: { label: "Mr. Compress Guide", url: "https://www.youtube.com/results?search_query=mr+compress+my+hero+ultra+rumble+guide" },
  },
];

const tiers = ["S", "A", "B", "C"];
