const characters = [
  {
    id: 1,
    name: "Deku",
    tier: "S",
    role: "Melee",
    bestCostume: "One For All: Full Cowl — 100%",
    costumes: [
      { name: "One For All: Full Cowl — 100%", best: true },
      { name: "Hero Costume (UA Sports Festival)", best: false },
      { name: "Vigilante Suit", best: false },
    ],
    tuning: [
      "Skill 1: Reduce cooldown — lets you spam Delaware Smash",
      "Skill 2: Increase damage — One For All: Full Cowl",
      "Skill 3: Increase range — Detroit Smash",
      "Passive: Increase HP recovery speed",
    ],
    tips: "Deku excels at aggressive close-range combat. Use Full Cowl to close gaps fast. Delaware Smash is your main combo starter — always tune its cooldown first. Great at flanking split teams.",
    video: { label: "Deku Combo Guide", url: "https://www.youtube.com/results?search_query=deku+my+hero+ultra+rumble+combo" },
  },
  {
    id: 2,
    name: "Bakugo",
    tier: "S",
    role: "Melee",
    bestCostume: "Battle Hero: Explosion",
    costumes: [
      { name: "Battle Hero: Explosion", best: true },
      { name: "UA Sports Festival", best: false },
      { name: "Provisional License Exam", best: false },
    ],
    tuning: [
      "Skill 1: Reduce cooldown — Stun Grenade",
      "Skill 2: Increase damage — AP Shot: Auto-Cannon",
      "Skill 3: Increase blast radius — Explosion Rush",
      "Passive: Increase attack speed",
    ],
    tips: "Bakugo is one of the top-tier characters for aggressive play. His Explosion Rush gives excellent mobility. Use Stun Grenade to lock enemies before dropping AP Shot. Always stay airborne to maximize damage.",
    video: { label: "Bakugo Combo Guide", url: "https://www.youtube.com/results?search_query=bakugo+my+hero+ultra+rumble+combo" },
  },
  {
    id: 3,
    name: "Toga",
    tier: "S",
    role: "Support / Melee",
    bestCostume: "League of Villains",
    costumes: [
      { name: "League of Villains", best: true },
      { name: "School Uniform", best: false },
      { name: "Villains Outfit Alt", best: false },
    ],
    tuning: [
      "Skill 1: Increase blood drain speed — Vampire",
      "Skill 2: Reduce transform cooldown — Transform",
      "Skill 3: Increase move speed during Transform",
      "Passive: HP recovery on kill",
    ],
    tips: "Toga is a high-skill character. Her Transform ability lets her copy enemies and use their moves. Best played by transforming into a high-damage enemy like Bakugo or Deku. Blood drain heals you — use it between fights.",
    video: { label: "Toga Combo Guide", url: "https://www.youtube.com/results?search_query=toga+my+hero+ultra+rumble+combo" },
  },
  {
    id: 4,
    name: "Hawks",
    tier: "S",
    role: "Ranged",
    bestCostume: "Pro Hero: Wings",
    costumes: [
      { name: "Pro Hero: Wings", best: true },
      { name: "Casual Wear", best: false },
      { name: "Provisional Exam", best: false },
    ],
    tuning: [
      "Skill 1: Increase feather count — Fierce Wings",
      "Skill 2: Reduce cooldown — Talons",
      "Skill 3: Increase flight speed",
      "Passive: Increase airborne damage",
    ],
    tips: "Hawks dominates with aerial mobility. Keep enemies at mid-range, pepper them with feathers, and dive in with Talons for the kill. His flight makes him very hard to pin down. Always stay moving — standing still loses you fights.",
    video: { label: "Hawks Combo Guide", url: "https://www.youtube.com/results?search_query=hawks+my+hero+ultra+rumble+combo" },
  },
  {
    id: 5,
    name: "Todoroki",
    tier: "A",
    role: "Ranged / Melee",
    bestCostume: "Hero Costume Ver. 2",
    costumes: [
      { name: "Hero Costume Ver. 2", best: true },
      { name: "UA Sports Festival", best: false },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "Skill 1: Increase ice range — Glacial Terrain",
      "Skill 2: Increase fire damage — Flashfire Fist",
      "Skill 3: Reduce cooldown — Heaven-Piercing Ice Wall",
      "Passive: Reduce temperature recovery time",
    ],
    tips: "Todoroki is a versatile fighter. Use ice moves to control zones and block enemy movement, then punish with fire combos. Ice Wall is great for cutting off escapes. His weakness is close-range burst — dodge and zone rather than trading.",
    video: { label: "Todoroki Combo Guide", url: "https://www.youtube.com/results?search_query=todoroki+my+hero+ultra+rumble+combo" },
  },
  {
    id: 6,
    name: "All Might",
    tier: "A",
    role: "Melee",
    bestCostume: "Golden Age Hero",
    costumes: [
      { name: "Golden Age Hero", best: true },
      { name: "Silver Age Hero", best: false },
      { name: "Casual (Yagi Toshinori)", best: false },
    ],
    tuning: [
      "Skill 1: Increase smash damage — Carolina Smash",
      "Skill 2: Reduce cooldown — Texas Smash",
      "Skill 3: Increase knockback — Detroit Smash",
      "Passive: Increase HP",
    ],
    tips: "All Might is a powerhouse with massive knockback. His smashes deal huge damage but are slow — predict enemy movement. Detroit Smash sends enemies flying for easy ring-outs. Weak at range, so close the gap fast.",
    video: { label: "All Might Combo Guide", url: "https://www.youtube.com/results?search_query=all+might+my+hero+ultra+rumble+combo" },
  },
  {
    id: 7,
    name: "Dabi",
    tier: "A",
    role: "Ranged",
    bestCostume: "League of Villains",
    costumes: [
      { name: "League of Villains", best: true },
      { name: "Villain Casual", best: false },
      { name: "Blueflame Alt", best: false },
    ],
    tuning: [
      "Skill 1: Increase fire duration — Cremation",
      "Skill 2: Increase range — Jet Burn",
      "Skill 3: Reduce cooldown — Blue Flame Barrage",
      "Passive: Increase burn damage",
    ],
    tips: "Dabi is a zone-control ranged character. His blue fire deals ongoing burn damage — spread flames across the floor to deny areas. Blue Flame Barrage is an excellent combo ender. He struggles in direct 1v1 melee so keep your distance.",
    video: { label: "Dabi Combo Guide", url: "https://www.youtube.com/results?search_query=dabi+my+hero+ultra+rumble+combo" },
  },
  {
    id: 8,
    name: "Shigaraki",
    tier: "A",
    role: "Melee",
    bestCostume: "League of Villains Leader",
    costumes: [
      { name: "League of Villains Leader", best: true },
      { name: "Villain Casual", best: false },
      { name: "Decay Form", best: false },
    ],
    tuning: [
      "Skill 1: Increase decay spread — Decay",
      "Skill 2: Increase damage — Scatter",
      "Skill 3: Reduce cooldown — Infrared Ray",
      "Passive: Increase decay range",
    ],
    tips: "Shigaraki is lethal at close range. Decay crumbles the terrain and deals massive area damage. Get in close, trigger Decay, and immediately Scatter. His weakness is sustained ranged pressure — use cover and approach from angles.",
    video: { label: "Shigaraki Combo Guide", url: "https://www.youtube.com/results?search_query=shigaraki+my+hero+ultra+rumble+combo" },
  },
  {
    id: 9,
    name: "Uraraka",
    tier: "B",
    role: "Support / Melee",
    bestCostume: "Hero Costume Ver. 2",
    costumes: [
      { name: "Hero Costume Ver. 2", best: true },
      { name: "UA Sports Festival", best: false },
      { name: "Casual Wear", best: false },
    ],
    tuning: [
      "Skill 1: Reduce cooldown — Zero Gravity",
      "Skill 2: Increase float duration — Meteor Storm",
      "Skill 3: Increase impact damage — Meteor Shower",
      "Passive: Increase air mobility",
    ],
    tips: "Uraraka is great for setting up kills. Use Zero Gravity on enemies to float them, then Meteor Storm to rain debris. She's weaker in solo 1v1 but excellent in team fights where allies can follow up on floated targets.",
    video: { label: "Uraraka Combo Guide", url: "https://www.youtube.com/results?search_query=uraraka+my+hero+ultra+rumble+combo" },
  },
  {
    id: 10,
    name: "Kirishima",
    tier: "B",
    role: "Melee / Tank",
    bestCostume: "Hero Costume: Hardening",
    costumes: [
      { name: "Hero Costume: Hardening", best: true },
      { name: "UA Sports Festival", best: false },
      { name: "Unbreakable Form", best: false },
    ],
    tuning: [
      "Skill 1: Increase armor duration — Hardening",
      "Skill 2: Increase damage — Red Riot Unbreakable",
      "Skill 3: Reduce knockback received",
      "Passive: Increase HP",
    ],
    tips: "Kirishima is a tanky frontliner. Hardening lets you absorb hits while countering. Unbreakable is his power move — activate when surrounded for a massive HP boost. He's best at protecting teammates and drawing aggro in team fights.",
    video: { label: "Kirishima Combo Guide", url: "https://www.youtube.com/results?search_query=kirishima+my+hero+ultra+rumble+combo" },
  },
];

const tiers = ["S", "A", "B", "C"];
